//cart actions
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CART_RESET = "CART_RESET";

//product actions
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL";
export const GET_PRODUCT_DETAILS_RESET = "GET_PRODUCT_DETAILS_RESET";

export const UPLOAD_PRODUCT_DETAILS_REQUEST = "UPLOAD_PRODUCT_DETAILS_REQUEST";
export const UPLOAD_PRODUCT_DETAILS_SUCCESS = "UPLOAD_PRODUCT_DETAILS_SUCCESS";
export const UPLOAD_PRODUCT_DETAILS_FAIL = "UPLOAD_PRODUCT_DETAILS_FAIL";

//auth actions
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';

//users
export const GET_CURRENT_USER_DATA_REQUEST = 'GET_CURRENT_USER_DATA_REQUEST';
export const GET_CURRENT_USER_DATA_SUCCESS = 'GET_CURRENT_USER_DATA_SUCCESS';
export const GET_CURRENT_USER_DATA_FAIL = 'GET_CURRENT_USER_DATA_FAIL';

export const USER_DATA_UPDATE_REQUEST = 'USER_DATA_UPDATE_REQUEST';
export const USER_DATA_UPDATE_SUCCESS = 'USER_DATA_UPDATE_SUCCESS';
export const USER_DATA_UPDATE_FAIL = 'USER_DATA_UPDATE_FAIL';

export const ON_USER_DETAILS_CHANGE = 'ON_USER_DETAILS_CHANGE';

//discussions
export const GET_DISCUSSIONS_REQUEST = 'GET_DISCUSSIONS_REQUEST';
export const GET_DISCUSSIONS_SUCCESS = 'GET_DISCUSSIONS_SUCCESS';
export const GET_DISCUSSIONS_FAIL = 'GET_DISCUSSIONS_FAIL';

export const GET_DISCUSSION_POST_REQUEST = 'GET_DISCUSSION_POST_REQUEST';
export const GET_DISCUSSION_POST_SUCCESS = 'GET_DISCUSSION_POST_SUCCESS';
export const GET_DISCUSSION_POST_FAIL = 'GET_DISCUSSION_POST_FAIL';

export const ADD_DISCUSSION_REQUEST = 'ADD_DISCUSSION_REQUEST';
export const ADD_DISCUSSION_SUCCESS = 'ADD_DISCUSSION_SUCCESS';
export const ADD_DISCUSSION_FAIL = 'ADD_DISCUSSION_FAIL';

export const DELETE_DISCUSSION_REQUEST = 'DELETE_DISCUSSION_REQUEST';
export const DELETE_DISCUSSION_SUCCESS = 'DELETE_DISCUSSION_SUCCESS';
export const DELETE_DISCUSSION_FAIL = 'DELETE_DISCUSSION_FAIL';

export const VOTE_DISCUSSION_SUCCESS = 'VOTE_DISCUSSION_SUCCESS'; //handles both upvotes and downvotes

//coments
export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';
